/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CebianlanIcon: typeof import('./src/components/CebianlanIcon.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    GameShow: typeof import('./src/components/GameShow.vue')['default']
    GongNeng: typeof import('./src/components/GongNeng.vue')['default']
    Guanli_cebian: typeof import('./src/components/Guanli_cebian.vue')['default']
    Jianli: typeof import('./src/components/Jianli.vue')['default']
    KanbanGirl: typeof import('./src/components/KanbanGirl.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    LogandReg: typeof import('./src/components/LogandReg.vue')['default']
    Lunbotu: typeof import('./src/components/Lunbotu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./src/components/SearchBox.vue')['default']
    Shipeidiannao: typeof import('./src/components/Shipeidiannao.vue')['default']
    Shipeishouji: typeof import('./src/components/Shipeishouji.vue')['default']
    Wordcloud: typeof import('./src/components/Wordcloud.vue')['default']
    Xiangmu: typeof import('./src/components/Xiangmu.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
